default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: <%= ENV.fetch('DB_USERNAME', 'username') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'password') %>
  host: <%= ENV.fetch('DB_HOST', nil) %>
